/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('http://localhost:3000/green.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ZBrush_defualt_group.geometry}
        material={materials['Material.002']}
        position={[0, 0.35, 0]}
      />
    </group>
  );
}

useGLTF.preload('http://localhost:3000/green.gltf');
