/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('http://localhost:3000/head.gltf');
  return (
    <group className='absolute z-50' ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ZBrush_defualt_group.geometry}
        material={nodes.ZBrush_defualt_group.material}
      />
    </group>
  );
}

useGLTF.preload('http://localhost:3000/head.gltf');
